# Change 'comments' to true for Disqus comments
# disqus:
#   comments: true
#   disqus_shortname: 'https-kciter-so'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-1'
google-ID: ''

menu:
# - {name: 'Writing', path: 'menu', url: 'writing'}
- {name: 'Teams', path: 'menu', url: 'team'}
- {name: 'Contact', path: 'menu', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: '→'
  previous_page: '←'

sharing_button_prompt: ''

related_posts: '연관 포스트'

post_date_prefix: 'Written on'
